In [1]:
import numpy as np
import pandas as pd


In [2]:
temp_df = pd.read_csv("../data/IMDB Dataset.csv")

In [3]:
temp_df.shape


(50000, 2)

In [4]:
#selecting 10000 rows only
df = temp_df.iloc[:10000]

In [5]:
df.shape

(10000, 2)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 156.4+ KB


In [7]:
df.head()


review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [8]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [9]:
df['sentiment'].value_counts()

positive    5028
negative    4972
Name: sentiment, dtype: int64

In [10]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [11]:
df.duplicated().sum()

17

In [12]:
duplicates = df.duplicated()

In [13]:
df[duplicates]

review sentiment
3537  Quite what the producers of this appalling ada...  negative
3769  My favourite police series of all time turns t...  positive
4391  Beautiful film, pure Cassavetes style. Gena Ro...  positive
6352  If you liked the Grinch movie... go watch that...  negative
6479  I want very much to believe that the above quo...  negative
6672  Sigh. I'm baffled when I see a short like this...  negative
7221  I have always been a huge fan of "Homicide: Li...  positive
7222  There are plenty of comments already posted sa...  negative
7425  The movie was excellent, save for some of the ...  positive
7555  This movie has made me upset! When I think of ...  negative
8040  Contains spoilers. <br /><br />The British dir...  negative
8801  Hilarious, clean, light-hearted, and quote-wor...  positive
8868  Ik know it is impossible to keep all details o...  negative
8874  From director Barbet Schroder (Reversal of For...  negative
9057  So, I'm wondering while watching this film, di...  negative
9503  This is one of those star-filled over-the-top ...  negative
9522  I watched this movie when Joe Bob Briggs hoste...  negative

In [14]:
# df_ = df[~duplicates] # to drop duplicates or
df.drop_duplicates(inplace=True)

/tmp/ipykernel_2217/942233371.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [15]:
df.shape

(9983, 2)

In [16]:
df.duplicated().sum()

0

### Basic preprocessing
### Remove Tags
### Lower Case
### Remove Stopwords

In [17]:
# function to remove tags
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'),'',raw_text)
    return cleaned_text

In [18]:
test = '<h1>Hi! I am manish.</h1>'
remove_tags(test)

'Hi! I am manish.'

In [19]:
df['review']=df['review'].apply(remove_tags)

/tmp/ipykernel_2217/2928534252.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_tags)


In [20]:
df['review'][1]

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [21]:
# convert the review to lower
df['review']=df['review'].apply(lambda x:x.lower())

/tmp/ipykernel_2217/2869280920.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(lambda x:x.lower())


In [22]:
# Removing the stopwords
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords

stop_words=stopwords.words('english')

df['review']=df['review'].apply(lambda x: [item for item in x.split() if item not in stop_words]).apply(lambda x:" ".join(x))

[nltk_data] Downloading package stopwords to /config/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
/tmp/ipykernel_2217/3062926908.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(lambda x: [item for item in x.split() if item not in stop_words]).apply(lambda x:" ".join(x))


In [23]:
df


review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [24]:
x = df.iloc[:,0:1]
y = df['sentiment']

In [25]:
x

review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [26]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [27]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,ytest = train_test_split(x,y,test_size=0.2,random_state=1)

In [29]:
print(x_train.shape,y_train.shape)

(7986, 1) (7986,)


In [30]:
# !applying Bow
from sklearn.feature_extraction.text import CountVectorizer

In [31]:
cv = CountVectorizer()

In [32]:
x_train_bow = cv.fit_transform(x_train['review']).toarray()
x_test_bow = cv.transform(x_test['review']).toarray()

In [33]:
x_train_bow.shape

(7986, 48282)

In [34]:
x_test_bow.shape

(1997, 48282)

In [35]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()


In [36]:
gnb.fit(x_train_bow,y_train)


: 

: 

In [ ]:

y_pred=gnb.predict(x_test_bow)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
accuracy_score(ytest,y_pred)

In [ ]:
confusion_matrix(ytest,y_pred)

array([[717, 235],
       [499, 546]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()



In [ ]:
rf.fit(x_train_bow,y_train)

RandomForestClassifier()

In [ ]:
y_pred = rf.predict(x_test_bow)

In [ ]:
accuracy_score(ytest,y_pred)

0.8492739108662994

In [ ]:
confusion_matrix(ytest,y_pred)

array([[808, 144],
       [157, 888]])

In [ ]:
# reducing the cv size to reduce training time

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=3000)
train_bow = cv.fit_transform(x_train['review']).toarray()
test_bow = cv.transform(x_test['review']).toarray()




In [ ]:
rf= RandomForestClassifier()

rf.fit(x_train_bow,y_train)


RandomForestClassifier()

In [ ]:
y_pred=rf.predict(x_test_bow)
accuracy_score(ytest,y_pred)

0.8512769153730596

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=3000)
train_bow = cv.fit_transform(x_train['review']).toarray()
test_bow = cv.transform(x_test['review']).toarray()
rf= RandomForestClassifier()

rf.fit(x_train_bow,y_train)

y_pred=rf.predict(x_test_bow)
accuracy_score(ytest,y_pred)

0.8462694041061593